Import('env', 'arch', 'messaging', 'common', 'visionipc', 'ASIUS_HARDWARE')

libs = [common, messaging, visionipc]

if arch != "Darwin":
  camera_obj = env.Object(['cameras/camera_v0.cc', 'cameras/cdm.cc', 'sensors/os04c10.cc'] if ASIUS_HARDWARE else
      ['cameras/camera_qcom2.cc', 'cameras/camera_common.cc', 'cameras/spectra.cc', 'cameras/cdm.cc', 'sensors/ox03c10.cc', 'sensors/os04c10.cc'])
  env.Program('camerad', ['main.cc', camera_obj], LIBS=libs)

  if GetOption('extras'):
    env.Program('test/test_camera_policy', ['test/test_camera_policy.cc', 'cameras/cdm.cc', 'sensors/os04c10.cc'], LIBS=libs)
